//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_exercises
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long ExType { get; set; }
        public Nullable<long> Category { get; set; }
        public string Description { get; set; }
        public string XmlData { get; set; }
        public int Visible { get; set; }
        public int Version { get; set; }
        public System.DateTime LastChange { get; set; }
    
        public virtual id_ExerTypes id_ExerTypes { get; set; }
        public virtual is_ExerSections is_ExerSections { get; set; }
    }
}
