//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_ExerSections
    {
        public is_ExerSections()
        {
            this.is_exercises = new HashSet<is_exercises>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentSection { get; set; }
    
        public virtual ICollection<is_exercises> is_exercises { get; set; }
    }
}
