//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_Langs
    {
        public is_Langs()
        {
            this.is_I18n = new HashSet<is_I18n>();
            this.is_SoundBaseTranslation = new HashSet<is_SoundBaseTranslation>();
            this.is_userdata = new HashSet<is_userdata>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public int Order { get; set; }
        public int Visible { get; set; }
    
        public virtual ICollection<is_I18n> is_I18n { get; set; }
        public virtual ICollection<is_SoundBaseTranslation> is_SoundBaseTranslation { get; set; }
        public virtual ICollection<is_userdata> is_userdata { get; set; }
    }
}
