//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_Modules
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public int Visible { get; set; }
        public string Settings { get; set; }
        public string BasedOnModule { get; set; }
        public int Version { get; set; }
        public System.DateTime LastChange { get; set; }
    }
}
