//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_Sessions
    {
        public System.Guid SessionId { get; set; }
        public long UserId { get; set; }
        public System.DateTime Time { get; set; }
        public string SessionData { get; set; }
    }
}
