//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_SoundBaseTranslation
    {
        public string Id { get; set; }
        public byte Type { get; set; }
        public string LangId { get; set; }
        public string Translation { get; set; }
    
        public virtual is_Langs is_Langs { get; set; }
    }
}
