//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_sound_exer_tries
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string PhraseId { get; set; }
        public System.DateTime TryTime { get; set; }
        public Nullable<int> Mark { get; set; }
        public string MarkDetails { get; set; }
        public string FileName { get; set; }
    }
}
