//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_Sections
    {
        public is_Sections()
        {
            this.is_Pages = new HashSet<is_Pages>();
            this.is_RegModulesToPages = new HashSet<is_RegModulesToPages>();
            this.is_Sections1 = new HashSet<is_Sections>();
            this.is_UserAccess = new HashSet<is_UserAccess>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string UrlName { get; set; }
        public Nullable<long> ParentSection { get; set; }
        public int Visible { get; set; }
        public string SectionSettings { get; set; }
        public int Order { get; set; }
        public short Type { get; set; }
        public System.DateTime LastChange { get; set; }
        public string FontImage { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<is_Pages> is_Pages { get; set; }
        public virtual ICollection<is_RegModulesToPages> is_RegModulesToPages { get; set; }
        public virtual ICollection<is_Sections> is_Sections1 { get; set; }
        public virtual is_Sections is_Sections2 { get; set; }
        public virtual ICollection<is_UserAccess> is_UserAccess { get; set; }
    }
}
