//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_SoundBaseInnerPhonemes
    {
        public string Id { get; set; }
        public short Position { get; set; }
        public decimal StartTime { get; set; }
        public decimal EndTime { get; set; }
        public string Transcription { get; set; }
        public Nullable<short> PhraseWordIndex { get; set; }
    }
}
