//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_SiteSettings
    {
        public long Id { get; set; }
        public string ValueName { get; set; }
        public string ValueStringData { get; set; }
        public Nullable<long> ValueIntData { get; set; }
        public byte[] ValueImageData { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ValueDoubleData { get; set; }
        public Nullable<bool> ValueBoolData { get; set; }
        public Nullable<System.DateTime> ValueDateData { get; set; }
    }
}
