//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_userdata
    {
        public is_userdata()
        {
            this.is_UserAccess = new HashSet<is_UserAccess>();
        }
    
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Language { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastAccessDate { get; set; }
        public string LastPageUrl { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int ExersLeft { get; set; }
        public decimal Money { get; set; }
        public string Theme { get; set; }
        public long Role { get; set; }
        public byte[] Image { get; set; }
        public long Id { get; set; }
        public long Salt { get; set; }
    
        public virtual is_Langs is_Langs { get; set; }
        public virtual ICollection<is_UserAccess> is_UserAccess { get; set; }
        public virtual is_UserRoles is_UserRoles { get; set; }
    }
}
