//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReplace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class main26Entities : DbContext
    {
        public main26Entities()
            : base("name=main26Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<id_ExerTypes> id_ExerTypes { get; set; }
        public virtual DbSet<is_exercises> is_exercises { get; set; }
        public virtual DbSet<is_ExerResults> is_ExerResults { get; set; }
        public virtual DbSet<is_ExerSections> is_ExerSections { get; set; }
        public virtual DbSet<is_I18n> is_I18n { get; set; }
        public virtual DbSet<is_Langs> is_Langs { get; set; }
        public virtual DbSet<is_Modules> is_Modules { get; set; }
        public virtual DbSet<is_Pages> is_Pages { get; set; }
        public virtual DbSet<is_RegisteredModules> is_RegisteredModules { get; set; }
        public virtual DbSet<is_Registration> is_Registration { get; set; }
        public virtual DbSet<is_RegModulesToPages> is_RegModulesToPages { get; set; }
        public virtual DbSet<is_ResetPassword> is_ResetPassword { get; set; }
        public virtual DbSet<is_Roles> is_Roles { get; set; }
        public virtual DbSet<is_Sections> is_Sections { get; set; }
        public virtual DbSet<is_Sessions> is_Sessions { get; set; }
        public virtual DbSet<is_SiteSettings> is_SiteSettings { get; set; }
        public virtual DbSet<is_sound_exer_progress> is_sound_exer_progress { get; set; }
        public virtual DbSet<is_sound_exer_tries> is_sound_exer_tries { get; set; }
        public virtual DbSet<is_SoundBaseInnerPhonemes> is_SoundBaseInnerPhonemes { get; set; }
        public virtual DbSet<is_SoundBasePhonemes> is_SoundBasePhonemes { get; set; }
        public virtual DbSet<is_SoundBaseTranslation> is_SoundBaseTranslation { get; set; }
        public virtual DbSet<is_SoundBaseWords> is_SoundBaseWords { get; set; }
        public virtual DbSet<is_Templates> is_Templates { get; set; }
        public virtual DbSet<is_user_ips> is_user_ips { get; set; }
        public virtual DbSet<is_UserAccess> is_UserAccess { get; set; }
        public virtual DbSet<is_userdata> is_userdata { get; set; }
        public virtual DbSet<is_UserRoles> is_UserRoles { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Memberships> Memberships { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
