//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordListPlugin
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_ExerResults
    {
        public string ExerName { get; set; }
        public System.DateTime Date { get; set; }
        public int Result { get; set; }
        public string InternalResults { get; set; }
        public long UserId { get; set; }
    }
}
