//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordListPlugin
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_I18n
    {
        public string Id { get; set; }
        public string Lang { get; set; }
        public string Value { get; set; }
        public long GroupId { get; set; }
        public int Type { get; set; }
    
        public virtual is_Langs is_Langs { get; set; }
    }
}
