//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordListPlugin
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_RegisteredModules
    {
        public is_RegisteredModules()
        {
            this.is_RegModulesToPages = new HashSet<is_RegModulesToPages>();
        }
    
        public long Id { get; set; }
        public string ModuleType { get; set; }
        public string Placeholder { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Settings { get; set; }
    
        public virtual ICollection<is_RegModulesToPages> is_RegModulesToPages { get; set; }
    }
}
